apiVersion: v1
kind: Service
metadata:
  name: mi-service
  namespace: vallegrande
spec:
  selector:
    app: mi-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
